/**
 * viz-texts.js
 * VIZ_TEXTS - Localization/i18n for Visual Studio
 * Turkish (tr) and English (en) translations
 */

(function () {
    'use strict';

    const VIZ_TEXTS = {
        tr: {
            viz_subtitle: 'Visual Studio',
            data_columns: 'Veri Sutunlari',
            drop_excel: 'Excel dosyasi surukleyin',
            no_data_loaded: 'Veri yukleyin',
            chart_types: 'Grafik Tipleri',
            chart_bar: 'Sutun',
            chart_line: 'Cizgi',
            chart_pie: 'Pasta',
            chart_area: 'Alan',
            chart_scatter: 'Dagilim',
            chart_doughnut: 'Halka',
            dashboard: 'Dashboard',
            live: 'CANLI',
            add_chart: 'Grafik Ekle',
            empty_dashboard_title: "Dashboard'unuz Bos",
            empty_dashboard_desc: 'Sol taraftan grafik tipini surukleyin veya "Grafik Ekle" butonuna tiklayin',
            chart_settings: 'Grafik Ayarlari',
            select_chart: 'Duzenlemek icin bir grafik secin',
            chart_title: 'Grafik Basligi',
            x_axis: 'X Ekseni (Kategori)',
            y_axis: 'Y Ekseni (Deger)',
            aggregation: 'Agregasyon',
            agg_sum: 'Toplam',
            agg_avg: 'Ortalama',
            agg_count: 'Sayi',
            agg_min: 'Minimum',
            agg_max: 'Maksimum',
            color: 'Renk',
            apply: 'Uygula',
            delete_chart: 'Grafigi Sil',
            save: 'Kaydet',
            export: 'Export',
            file_loaded: 'Dosya yuklendi',
            error: 'Hata',
            chart_added: 'Grafik eklendi',
            // Coklu Y Ekseni ve Dual Axis
            y_axes: 'Y Eksenleri (Degerler)',
            multi_select_hint: 'Ctrl+Click ile coklu secim',
            use_right_axis: 'Ikinci seriyi sag eksende goster',
            right_axis_column: 'Sag Eksen Sutunu',
            scatter_x_hint: 'Scatter icin coklu X secimi aktif (Ctrl+Click)',
            // Faz 1 yeni metinler
            export_png: 'PNG olarak indir',
            export_pdf: 'PDF olarak indir',
            save_dashboard: 'Dashboard kaydet',
            load_dashboard: 'Dashboard yukle',
            dashboard_saved: 'Dashboard kaydedildi',
            dashboard_loaded: 'Dashboard yuklendi',
            no_saved_dashboard: 'Kayitli dashboard bulunamadi',
            export_success: 'Export basarili',
            loading: 'Yukleniyor...',
            // Faz 2 istatistik metinleri
            stats_overlay: 'Istatistik Overlay',
            show_mean: 'Ortalama Cizgisi',
            show_median: 'Medyan Cizgisi',
            show_std_band: 'Standart Sapma Bandi (+-1s)',
            show_trend: 'Trend Cizgisi',
            stats_summary: 'Istatistik Ozeti',
            stat_mean: 'Ortalama',
            stat_median: 'Medyan',
            stat_stdev: 'Std Sapma',
            stat_min: 'Min',
            stat_max: 'Maks',
            stat_count: 'Sayi',
            // Faz 3 ileri grafik metinleri
            basic_charts: 'Temel',
            advanced_charts: 'Ileri',
            chart_dual_axis: 'Dual-Axis',
            chart_stacked: 'Yigin',
            chart_treemap: 'Treemap',
            chart_heatmap: 'Isi Haritasi',
            chart_funnel: 'Huni',
            chart_gauge: 'Gosterge',
            chart_waterfall: 'Selale',
            chart_radar: 'Radar',
            chart_boxplot: 'Kutu',
            chart_pareto: 'Pareto',
            // Faz 4 3D grafik metinleri
            '3d_charts': '3D',
            chart_scatter3d: '3D Dagilim',
            chart_bar3d: '3D Sutun',
            chart_surface3d: '3D Yuzey',
            chart_line3d: '3D Cizgi',
            // Faz 5-9 yeni metinler
            statistical_analysis: 'Istatistiksel Analiz',
            bi_insights: 'BI Icgoruleri',
            data_profile: 'Veri Profili',
            run_analysis: 'Analiz Calistir',
            what_if_simulator: 'Ne Olur Simulatoru',
            anomaly_detection: 'Anomali Tespiti',
            trend_insight: 'Trend Icgorusu',
            regression_type: 'Regresyon Tipi',
            linear: 'Dogrusal',
            polynomial: 'Polinom',
            exponential: 'Ustel',
            logarithmic: 'Logaritmik',
            t_test: 't-Test',
            anova: 'ANOVA',
            correlation: 'Korelasyon',
            normality: 'Normallik',
            cross_filter: 'Capraz Filtre',
            detect_anomalies: 'Anomali Tespit',
            anomalies_found: 'anomali bulundu',
            no_anomaly: 'Anomali tespit edilmedi',
            trend_up: 'Yukari yonlu trend',
            trend_down: 'Asagi yonlu trend',
            trend_stable: 'Stabil (belirgin trend yok)',
            data_analysis: 'Veri Analizi',
            total_rows: 'Toplam Satir',
            total_columns: 'Toplam Sutun',
            data_quality: 'Veri Kalitesi',
            column_types: 'Sutun Tipleri',
            missing_values: 'Eksik Degerler',
            no_missing: 'Eksik deger yok',
            // Faz 6 - Yeni Modal Metinleri
            google_sheets_title: 'Google Sheets Baglantisi',
            google_sheets_desc: 'Google Sheets\'ten veri cekmek icin Spreadsheet ID girin veya OAuth ile baglanin.',
            spreadsheet_id: 'Spreadsheet ID',
            spreadsheet_id_hint: 'URL\'deki /d/ ile /edit arasindaki kod',
            sheet_name: 'Sayfa Adi (opsiyonel)',
            fetch_data: 'Veriyi Cek',
            connect_google: 'Google ile Baglan (OAuth)',
            sql_title: 'SQL Veri Kaynagi',
            connection_string: 'Baglanti String\'i',
            connection_hint: 'PostgreSQL, MySQL, SQLite, SQL Server desteklenir',
            test_connection: 'Baglantiyi Test Et',
            sql_query: 'SQL Sorgusu (sadece SELECT)',
            max_rows: 'Max Satir',
            run_query: 'Sorguyu Calistir',
            tables: 'Tablolar',
            collab_title: 'Canli Isbirligi',
            collab_desc: 'Ayni dashboard uzerinde gercek zamanli calisin.',
            room_id: 'Oda ID',
            username: 'Kullanici Adi',
            join_room: 'Odaya Katil',
            connected: 'Bagli',
            users: 'Kullanici',
            schedule_title: 'Zamanlanmis Raporlar',
            report_name: 'Rapor Adi',
            recipients: 'Alicilar (virgulle ayirin)',
            period: 'Periyot',
            daily: 'Gunluk',
            weekly: 'Haftalik',
            monthly: 'Aylik',
            time: 'Saat',
            format: 'Format',
            create_report: 'Rapor Olustur',
            existing_reports: 'Mevcut Raporlar',
            active: 'Aktif',
            inactive: 'Pasif',
            stop: 'Durdur',
            start: 'Baslat',
            run_now: 'Simdi Calistir',
            join_title: 'Veri Birlestirme (JOIN)',
            left_table: 'Sol Tablo',
            right_table: 'Sag Tablo',
            left_key: 'Sol Anahtar Sutun',
            right_key: 'Sag Anahtar Sutun',
            join_type: 'Birlestirme Tipi',
            left_join: 'Left Join (Sol tablo tum satirlar)',
            inner_join: 'Inner Join (Ortak satirlar)',
            outer_join: 'Outer Join (Tum satirlar)',
            right_join: 'Right Join (Sag tablo tum satirlar)',
            merge: 'Birlestir',
            merging: 'Birlestiriliyor...',
            merged_success: 'Birlestirildi!',
            rows_created: 'satir olusturuldu',
            regression_title: 'Regresyon Analizi',
            target_variable: 'Hedef Degisken (Y)',
            predictor_variables: 'Tahmin Degiskenleri (X)',
            regression_type_label: 'Regresyon Tipi',
            linear_reg: 'Dogrusal (Linear)',
            polynomial_reg: 'Polinom (2. derece)',
            logistic_reg: 'Logistic (Binary hedef icin)',
            analyze: 'Analiz Et',
            coefficients: 'Katsayilar',
            regression_complete: 'Regresyon tamamlandi',
            insights_title: 'Akilli Icgoruler',
            analyzed: 'Analiz Edilen',
            rows: 'satir',
            columns: 'sutun',
            add_as_widget: 'Widget Olarak Ekle',
            calculating_insights: 'Icgoruler hesaplaniyor...',
            need_two_datasets: 'JOIN icin en az 2 veri seti gerekli. Once iki dosya yukleyin.',
            dataset_files_not_found: 'Veri seti dosyalari bulunamadi',
            load_data_first: 'Once dosya yukleyin',
            need_two_numeric: 'Regresyon icin en az 2 sayisal sutun gerekli',
            select_one_predictor: 'En az 1 tahmin degiskeni secin',
            spreadsheet_id_required: 'Spreadsheet ID gerekli',
            connection_required: 'Baglanti ve sorgu gerekli',
            room_id_required: 'Oda ID gerekli',
            report_name_required: 'Rapor adi ve en az 1 alici gerekli',
            connection_success: 'Baglanti basarili!',
            joined_room: 'odasina baglandi!',
            left_room: 'Isbirligi odasindan cikildi',
            connection_closed: 'Isbirligi baglantisi kapandi',
            user_joined: 'odaya katildi',
            user_left: 'odadan ayrildi',
            loading_reports: 'Yukleniyor...',
            no_reports_yet: 'Henuz zamanlanmis rapor yok',
            oauth_window_opened: 'Google OAuth penceresi acildi',
            loaded_from_sheets: 'satir Google Sheets\'ten yuklendi',
            loaded_from_sql: 'satir SQL\'den yuklendi',
            row_limit: 'satir limiti',
            // PDF Preview & Eksik Anahtarlar
            pdf_preview: 'PDF Onizleme',
            download_pdf: 'PDF Indir',
            close: 'Kapat',
            statistics: 'Istatistik Analizleri',
            special_charts: 'Ozel Grafikler',
            map_charts: 'Harita Grafikleri',
            data_management: 'Veri Yonetimi',
            select_dataset: 'Veri Seti',
            theme_changed: 'Tema degistirildi',
            pdf_generating: 'PDF olusturuluyor...',
            pdf_ready: 'PDF hazir'
        },

        en: {
            viz_subtitle: 'Visual Studio',
            data_columns: 'Data Columns',
            drop_excel: 'Drop Excel file here',
            no_data_loaded: 'Load data',
            chart_types: 'Chart Types',
            chart_bar: 'Bar',
            chart_line: 'Line',
            chart_pie: 'Pie',
            chart_area: 'Area',
            chart_scatter: 'Scatter',
            chart_doughnut: 'Doughnut',
            dashboard: 'Dashboard',
            live: 'LIVE',
            add_chart: 'Add Chart',
            empty_dashboard_title: 'Your Dashboard is Empty',
            empty_dashboard_desc: 'Drag a chart type from left panel or click "Add Chart"',
            chart_settings: 'Chart Settings',
            select_chart: 'Select a chart to edit',
            chart_title: 'Chart Title',
            x_axis: 'X Axis (Category)',
            y_axis: 'Y Axis (Value)',
            aggregation: 'Aggregation',
            agg_sum: 'Sum',
            agg_avg: 'Average',
            agg_count: 'Count',
            agg_min: 'Minimum',
            agg_max: 'Maximum',
            color: 'Color',
            apply: 'Apply',
            delete_chart: 'Delete Chart',
            save: 'Save',
            export: 'Export',
            file_loaded: 'File loaded',
            error: 'Error',
            chart_added: 'Chart added',
            // Faz 1 yeni metinler
            export_png: 'Download as PNG',
            export_pdf: 'Download as PDF',
            save_dashboard: 'Save Dashboard',
            load_dashboard: 'Load Dashboard',
            dashboard_saved: 'Dashboard saved',
            dashboard_loaded: 'Dashboard loaded',
            no_saved_dashboard: 'No saved dashboard found',
            export_success: 'Export successful',
            loading: 'Loading...',
            // Faz 2 istatistik metinleri
            stats_overlay: 'Statistics Overlay',
            show_mean: 'Mean Line',
            show_median: 'Median Line',
            show_std_band: 'Std Deviation Band (+-1s)',
            show_trend: 'Trend Line',
            stats_summary: 'Statistics Summary',
            stat_mean: 'Mean',
            stat_median: 'Median',
            stat_stdev: 'Std Dev',
            stat_min: 'Min',
            stat_max: 'Max',
            stat_count: 'Count',
            // Faz 3 ileri grafik metinleri
            basic_charts: 'Basic',
            advanced_charts: 'Advanced',
            chart_dual_axis: 'Dual-Axis',
            chart_stacked: 'Stacked',
            chart_treemap: 'Treemap',
            chart_heatmap: 'Heatmap',
            chart_funnel: 'Funnel',
            chart_gauge: 'Gauge',
            chart_waterfall: 'Waterfall',
            chart_radar: 'Radar',
            chart_boxplot: 'Box Plot',
            chart_pareto: 'Pareto',
            // Faz 4 3D grafik metinleri
            '3d_charts': '3D',
            chart_scatter3d: '3D Scatter',
            chart_bar3d: '3D Bar',
            chart_surface3d: '3D Surface',
            chart_line3d: '3D Line',
            // Faz 5-9 yeni metinler
            statistical_analysis: 'Statistical Analysis',
            bi_insights: 'BI Insights',
            data_profile: 'Data Profile',
            run_analysis: 'Run Analysis',
            what_if_simulator: 'What-If Simulator',
            anomaly_detection: 'Anomaly Detection',
            trend_insight: 'Trend Insight',
            regression_type: 'Regression Type',
            linear: 'Linear',
            polynomial: 'Polynomial',
            exponential: 'Exponential',
            logarithmic: 'Logarithmic',
            t_test: 't-Test',
            anova: 'ANOVA',
            correlation: 'Correlation',
            normality: 'Normality',
            cross_filter: 'Cross Filter',
            detect_anomalies: 'Detect Anomalies',
            anomalies_found: 'anomalies found',
            no_anomaly: 'No anomaly detected',
            trend_up: 'Upward trend detected',
            trend_down: 'Downward trend detected',
            trend_stable: 'Stable (no significant trend)',
            data_analysis: 'Data Analysis',
            total_rows: 'Total Rows',
            total_columns: 'Total Columns',
            data_quality: 'Data Quality',
            column_types: 'Column Types',
            missing_values: 'Missing Values',
            no_missing: 'No missing values',
            // Faz 6 - New Modal Texts
            google_sheets_title: 'Google Sheets Connection',
            google_sheets_desc: 'Enter Spreadsheet ID to fetch data from Google Sheets or connect via OAuth.',
            spreadsheet_id: 'Spreadsheet ID',
            spreadsheet_id_hint: 'Code between /d/ and /edit in URL',
            sheet_name: 'Sheet Name (optional)',
            fetch_data: 'Fetch Data',
            connect_google: 'Connect with Google (OAuth)',
            sql_title: 'SQL Data Source',
            connection_string: 'Connection String',
            connection_hint: 'PostgreSQL, MySQL, SQLite, SQL Server supported',
            test_connection: 'Test Connection',
            sql_query: 'SQL Query (SELECT only)',
            max_rows: 'Max Rows',
            run_query: 'Run Query',
            tables: 'Tables',
            collab_title: 'Live Collaboration',
            collab_desc: 'Work together on the same dashboard in real-time.',
            room_id: 'Room ID',
            username: 'Username',
            join_room: 'Join Room',
            connected: 'Connected',
            users: 'User',
            schedule_title: 'Scheduled Reports',
            report_name: 'Report Name',
            recipients: 'Recipients (comma separated)',
            period: 'Period',
            daily: 'Daily',
            weekly: 'Weekly',
            monthly: 'Monthly',
            time: 'Time',
            format: 'Format',
            create_report: 'Create Report',
            existing_reports: 'Existing Reports',
            active: 'Active',
            inactive: 'Inactive',
            stop: 'Stop',
            start: 'Start',
            run_now: 'Run Now',
            join_title: 'Data Join (JOIN)',
            left_table: 'Left Table',
            right_table: 'Right Table',
            left_key: 'Left Key Column',
            right_key: 'Right Key Column',
            join_type: 'Join Type',
            left_join: 'Left Join (All rows from left)',
            inner_join: 'Inner Join (Common rows)',
            outer_join: 'Outer Join (All rows)',
            right_join: 'Right Join (All rows from right)',
            merge: 'Merge',
            merging: 'Merging...',
            merged_success: 'Merged!',
            rows_created: 'rows created',
            regression_title: 'Regression Analysis',
            target_variable: 'Target Variable (Y)',
            predictor_variables: 'Predictor Variables (X)',
            regression_type_label: 'Regression Type',
            linear_reg: 'Linear',
            polynomial_reg: 'Polynomial (2nd degree)',
            logistic_reg: 'Logistic (For binary target)',
            analyze: 'Analyze',
            coefficients: 'Coefficients',
            regression_complete: 'Regression complete',
            insights_title: 'Smart Insights',
            analyzed: 'Analyzed',
            rows: 'rows',
            columns: 'columns',
            add_as_widget: 'Add as Widget',
            calculating_insights: 'Calculating insights...',
            need_two_datasets: 'At least 2 datasets required for JOIN. Load two files first.',
            dataset_files_not_found: 'Dataset files not found',
            load_data_first: 'Load a file first',
            need_two_numeric: 'At least 2 numeric columns required for regression',
            select_one_predictor: 'Select at least 1 predictor variable',
            spreadsheet_id_required: 'Spreadsheet ID required',
            connection_required: 'Connection and query required',
            room_id_required: 'Room ID required',
            report_name_required: 'Report name and at least 1 recipient required',
            connection_success: 'Connection successful!',
            joined_room: 'joined room!',
            left_room: 'Left collaboration room',
            connection_closed: 'Collaboration connection closed',
            user_joined: 'joined the room',
            user_left: 'left the room',
            loading_reports: 'Loading...',
            no_reports_yet: 'No scheduled reports yet',
            oauth_window_opened: 'Google OAuth window opened',
            loaded_from_sheets: 'rows loaded from Google Sheets',
            loaded_from_sql: 'rows loaded from SQL',
            row_limit: 'row limit',
            // PDF Preview & Missing Keys
            pdf_preview: 'PDF Preview',
            download_pdf: 'Download PDF',
            close: 'Close',
            statistics: 'Statistical Analysis',
            special_charts: 'Special Charts',
            map_charts: 'Map Charts',
            data_management: 'Data Management',
            select_dataset: 'Dataset',
            theme_changed: 'Theme changed',
            pdf_generating: 'Generating PDF...',
            pdf_ready: 'PDF ready',
            // Multi-series Y axis and Dual Axis
            y_axes: 'Y Axes (Values)',
            multi_select_hint: 'Ctrl+Click for multiple selection',
            use_right_axis: 'Show second series on right axis',
            right_axis_column: 'Right Axis Column',
            scatter_x_hint: 'Multi-X selection enabled for Scatter (Ctrl+Click)'
        }
    };

    /**
     * VIZ_TEXTS'ten aktif dile gore metin alir
     * @param {string} key - Lokalizasyon anahtari
     * @param {string} fallback - Bulunamazsa donecek deger (opsiyonel)
     * @returns {string} Cevrilmis metin
     */
    function getText(key, fallback = '') {
        const state = window.VIZ_STATE;
        const lang = state ? state.lang : 'tr';
        const texts = VIZ_TEXTS[lang] || VIZ_TEXTS.tr;
        return texts[key] || VIZ_TEXTS.tr[key] || fallback || key;
    }

    // Global exports
    window.VIZ_TEXTS = VIZ_TEXTS;
    window.getText = getText;

    console.log('✅ viz-texts.js Loaded');
})();
