// =====================================================
// TEXTS.JS - Opradox Visual Studio Localization
// TR/EN Language Texts
// =====================================================

export const VIZ_TEXTS = {
    tr: {
        viz_subtitle: 'Visual Studio',
        module_excel: 'Excel Studio',
        module_viz: 'Visual Studio',
        module_pdf: 'PDF Tools',
        module_ocr: 'OCR Lab',
        data_columns: 'Veri Sütunları',
        drop_excel: 'Excel dosyası sürükleyin',
        no_data_loaded: 'Veri yükleyin',
        chart_types: 'Grafik Tipleri',
        chart_bar: 'Sütun',
        chart_line: 'Çizgi',
        chart_pie: 'Pasta',
        chart_area: 'Alan',
        chart_scatter: 'Dağılım',
        chart_doughnut: 'Halka',
        dashboard: 'Dashboard',
        live: 'CANLI',
        add_chart: 'Grafik Ekle',
        empty_dashboard_title: "Dashboard'unuz Boş",
        empty_dashboard_desc: 'Sol taraftan grafik tipini sürükleyin veya "Grafik Ekle" butonuna tıklayın',
        chart_settings: 'Grafik Ayarları',
        select_chart: 'Düzenlemek için bir grafik seçin',
        chart_title: 'Grafik Başlığı',
        x_axis: 'X Ekseni (Kategori)',
        y_axis: 'Y Ekseni (Değer)',
        aggregation: 'Agregasyon',
        agg_sum: 'Toplam',
        agg_avg: 'Ortalama',
        agg_count: 'Sayı',
        agg_min: 'Minimum',
        agg_max: 'Maksimum',
        color: 'Renk',
        apply: 'Uygula',
        delete_chart: 'Grafiği Sil',
        save: 'Kaydet',
        export: 'Export',
        file_loaded: 'Dosya yüklendi',
        error: 'Hata',
        chart_added: 'Grafik eklendi',
        y_axes: 'Y Eksenleri (Değerler)',
        multi_select_hint: 'Ctrl+Click ile çoklu seçim',
        use_right_axis: 'İkinci seriyi sağ eksende göster',
        right_axis_column: 'Sağ Eksen Sütunu',
        scatter_x_hint: 'Scatter için çoklu X seçimi aktif (Ctrl+Click)',
        export_png: 'PNG olarak indir',
        export_pdf: 'PDF olarak indir',
        save_dashboard: 'Dashboard kaydet',
        load_dashboard: 'Dashboard yükle',
        dashboard_saved: 'Dashboard kaydedildi',
        dashboard_loaded: 'Dashboard yüklendi',
        no_saved_dashboard: 'Kayıtlı dashboard bulunamadı',
        export_success: 'Export başarılı',
        loading: 'Yükleniyor...',
        stats_overlay: 'İstatistik Overlay',
        show_mean: 'Ortalama Çizgisi',
        show_median: 'Medyan Çizgisi',
        show_std_band: 'Standart Sapma Bandı (±1σ)',
        show_trend: 'Trend Çizgisi',
        stats_summary: 'İstatistik Özeti',
        stat_mean: 'Ortalama',
        stat_median: 'Medyan',
        stat_stdev: 'Std Sapma',
        stat_min: 'Min',
        stat_max: 'Maks',
        stat_count: 'Sayı',
        basic_charts: 'Temel',
        advanced_charts: 'İleri',
        chart_dual_axis: 'Dual-Axis',
        chart_stacked: 'Yığın',
        chart_treemap: 'Treemap',
        chart_heatmap: 'Isı Haritası',
        chart_funnel: 'Huni',
        chart_gauge: 'Gösterge',
        chart_waterfall: 'Şelale',
        chart_radar: 'Radar',
        chart_boxplot: 'Kutu',
        chart_pareto: 'Pareto',
        '3d_charts': '3D',
        chart_scatter3d: '3D Dağılım',
        chart_bar3d: '3D Sütun',
        chart_surface3d: '3D Yüzey',
        chart_line3d: '3D Çizgi',
        statistical_analysis: 'İstatistiksel Analiz',
        bi_insights: 'BI İçgörüleri',
        data_profile: 'Veri Profili',
        run_analysis: 'Analiz Çalıştır',
        what_if_simulator: 'Ne Olur Simülatörü',
        anomaly_detection: 'Anomali Tespiti',
        trend_insight: 'Trend İçgörüsü',
        regression_type: 'Regresyon Tipi',
        linear: 'Doğrusal',
        polynomial: 'Polinom',
        exponential: 'Üstel',
        logarithmic: 'Logaritmik',
        t_test: 't-Test',
        anova: 'ANOVA',
        correlation: 'Korelasyon',
        normality: 'Normallik',
        cross_filter: 'Çapraz Filtre',
        detect_anomalies: 'Anomali Tespit',
        anomalies_found: 'anomali bulundu',
        no_anomaly: 'Anomali tespit edilmedi ✓',
        trend_up: 'Yukarı yönlü trend',
        trend_down: 'Aşağı yönlü trend',
        trend_stable: 'Stabil (belirgin trend yok)',
        data_analysis: 'Veri Analizi',
        total_rows: 'Toplam Satır',
        total_columns: 'Toplam Sütun',
        data_quality: 'Veri Kalitesi',
        column_types: 'Sütun Tipleri',
        missing_values: 'Eksik Değerler',
        no_missing: 'Eksik değer yok ✓',
        google_sheets_title: 'Google Sheets Bağlantısı',
        google_sheets_desc: 'Google Sheets\'ten veri çekmek için Spreadsheet ID girin veya OAuth ile bağlanın.',
        spreadsheet_id: 'Spreadsheet ID',
        spreadsheet_id_hint: 'URL\'deki /d/ ile /edit arasındaki kod',
        sheet_name: 'Sayfa Adı (opsiyonel)',
        fetch_data: 'Veriyi Çek',
        connect_google: 'Google ile Bağlan (OAuth)',
        sql_title: 'SQL Veri Kaynağı',
        connection_string: 'Bağlantı String\'i',
        connection_hint: 'PostgreSQL, MySQL, SQLite, SQL Server desteklenir',
        test_connection: 'Bağlantıyı Test Et',
        sql_query: 'SQL Sorgusu (sadece SELECT)',
        max_rows: 'Max Satır',
        run_query: 'Sorguyu Çalıştır',
        tables: 'Tablolar',
        collab_title: 'Canlı İşbirliği',
        collab_desc: 'Aynı dashboard üzerinde gerçek zamanlı çalışın.',
        room_id: 'Oda ID',
        username: 'Kullanıcı Adı',
        join_room: 'Odaya Katıl',
        connected: 'Bağlı',
        users: 'Kullanıcı',
        schedule_title: 'Zamanlanmış Raporlar',
        report_name: 'Rapor Adı',
        recipients: 'Alıcılar (virgülle ayırın)',
        period: 'Periyot',
        daily: 'Günlük',
        weekly: 'Haftalık',
        monthly: 'Aylık',
        time: 'Saat',
        format: 'Format',
        create_report: 'Rapor Oluştur',
        existing_reports: 'Mevcut Raporlar',
        active: 'Aktif',
        inactive: 'Pasif',
        stop: 'Durdur',
        start: 'Başlat',
        run_now: 'Şimdi Çalıştır',
        join_title: 'Veri Birleştirme (JOIN)',
        left_table: 'Sol Tablo',
        right_table: 'Sağ Tablo',
        left_key: 'Sol Anahtar Sütun',
        right_key: 'Sağ Anahtar Sütun',
        join_type: 'Birleştirme Tipi',
        left_join: 'Left Join (Sol tablo tüm satırlar)',
        inner_join: 'Inner Join (Ortak satırlar)',
        outer_join: 'Outer Join (Tüm satırlar)',
        right_join: 'Right Join (Sağ tablo tüm satırlar)',
        merge: 'Birleştir',
        merging: 'Birleştiriliyor...',
        merged_success: 'Birleştirildi!',
        rows_created: 'satır oluşturuldu',
        regression_title: 'Regresyon Analizi',
        target_variable: 'Hedef Değişken (Y)',
        predictor_variables: 'Tahmin Değişkenleri (X)',
        regression_type_label: 'Regresyon Tipi',
        linear_reg: 'Doğrusal (Linear)',
        polynomial_reg: 'Polinom (2. derece)',
        logistic_reg: 'Logistic (Binary hedef için)',
        analyze: 'Analiz Et',
        coefficients: 'Katsayılar',
        regression_complete: 'Regresyon tamamlandı',
        insights_title: 'Akıllı İçgörüler',
        analyzed: 'Analiz Edilen',
        rows: 'satır',
        columns: 'sütun',
        add_as_widget: 'Widget Olarak Ekle',
        calculating_insights: 'İçgörüler hesaplanıyor...',
        need_two_datasets: 'JOIN için en az 2 veri seti gerekli. Önce iki dosya yükleyin.',
        dataset_files_not_found: 'Veri seti dosyaları bulunamadı',
        load_data_first: 'Önce dosya yükleyin',
        need_two_numeric: 'Regresyon için en az 2 sayısal sütun gerekli',
        select_one_predictor: 'En az 1 tahmin değişkeni seçin',
        spreadsheet_id_required: 'Spreadsheet ID gerekli',
        connection_required: 'Bağlantı ve sorgu gerekli',
        room_id_required: 'Oda ID gerekli',
        report_name_required: 'Rapor adı ve en az 1 alıcı gerekli',
        connection_success: 'Bağlantı başarılı!',
        joined_room: 'odasına bağlandı!',
        left_room: 'İşbirliği odasından çıkıldı',
        connection_closed: 'İşbirliği bağlantısı kapandı',
        user_joined: 'odaya katıldı',
        user_left: 'odadan ayrıldı',
        loading_reports: 'Yükleniyor...',
        no_reports_yet: 'Henüz zamanlanmış rapor yok',
        oauth_window_opened: 'Google OAuth penceresi açıldı',
        loaded_from_sheets: 'satır Google Sheets\'ten yüklendi',
        loaded_from_sql: 'satır SQL\'den yüklendi',
        row_limit: 'satır limiti',
        pdf_preview: 'PDF Önizleme',
        download_pdf: 'PDF İndir',
        close: 'Kapat',
        statistics: 'İstatistik Analizleri',
        special_charts: 'Özel Grafikler',
        map_charts: 'Harita Grafikleri',
        data_management: 'Veri Yönetimi',
        select_dataset: 'Veri Seti',
        theme_changed: 'Tema değiştirildi',
        pdf_generating: 'PDF oluşturuluyor...',
        pdf_ready: 'PDF hazır',

        // ===== NEW TRANSLATIONS - Data Management Actions =====
        action_filter: 'Filtrele',
        action_sort: 'Sırala',
        action_profile: 'Profil',
        action_undo: 'Geri Al',
        action_redo: 'İleri Al',
        action_fill_missing: 'Eksik Doldur',
        action_remove_outliers: 'Aykırı Temizle',
        action_remove_duplicates: 'Kopyaları Sil',
        action_convert_type: 'Tip Dönüştür',
        action_merge_columns: 'Kolon Birleştir',
        action_split_column: 'Kolon Böl',
        action_find_replace: 'Bul/Değiştir',
        action_binning: 'Binning',
        action_pivot: 'Pivot',
        action_calculated: 'Hesaplanan',
        action_load_url: "URL'den Yükle",
        action_add_file: 'Dosya Ekle',

        // ===== NEW TRANSLATIONS - Tools =====
        tools_category: 'Araçlar',
        tool_watermark: 'Watermark',
        tool_report_settings: 'Rapor Ayarları',
        tool_video_help: 'Video Yardım',
        tool_export_annotated: 'Notlu Export',

        // ===== NEW TRANSLATIONS - Stat Buttons =====
        drag_to_dashboard: '🎯 Dashboard\'a sürükle',
        stat_ttest: 't-Test',
        stat_anova: 'ANOVA',
        stat_chi: 'Chi²',
        stat_correlation: 'Korelasyon',
        stat_normality: 'Normallik',
        stat_descriptive: 'Betimsel',
        stat_mannwhitney: 'Mann-Whitney',
        stat_wilcoxon: 'Wilcoxon',
        stat_kruskal: 'Kruskal-Wallis',
        stat_levene: 'Levene',
        stat_effect_size: 'Effect Size',
        stat_frequency: 'Frekans',
        stat_pca: 'PCA',
        stat_kmeans: 'K-Means',
        stat_cronbach: 'Cronbach α',
        stat_logistic: 'Lojistik Reg.',
        stat_timeseries: 'Zaman Serisi',
        stat_apa: 'APA Raporu',
        stat_friedman: 'Friedman',
        stat_power: 'Power Analysis',
        stat_regression: 'Regresyon',
        stat_discriminant: 'Discriminant',
        stat_survival: 'Sağkalım',

        // ===== NEW TRANSLATIONS - Special Charts =====
        chart_histogram: 'Histogram',
        chart_bubble: 'Bubble',
        chart_sankey: 'Sankey',
        chart_sunburst: 'Sunburst',
        chart_polar: 'Polar',
        chart_lollipop: 'Lollipop',
        chart_bullet: 'Bullet',
        chart_step: 'Step Line',
        chart_calendar: 'Takvim',
        chart_candlestick: 'Mum',
        chart_violin: 'Violin',
        chart_gantt: 'Gantt',
        chart_grouped_bar: 'Gruplu Bar',
        chart_word_cloud: 'Kelime Bulutu',
        chart_timeline: 'Timeline',
        chart_chord: 'Chord',
        chart_parallel: 'Parallel',
        chart_range_area: 'Range Area',
        chart_density: 'Yoğunluk',

        // ===== FAZ-ST4: Coming Soon Charts =====
        coming_soon_charts: 'Yakında',
        coming_soon: 'Yakında',
        chart_globe: 'Globe',
        chart_graph: 'Graph',

        // ===== VIRAL-1: Try Demo =====
        try_demo: 'Demo Dene | Try Demo',

        // ===== VIRAL-2: Standalone HTML =====
        standalone_html: 'Standalone HTML ✈️',
        standalone_html_creating: 'Standalone HTML oluşturuluyor...',
        standalone_html_success: 'Standalone HTML indirildi - Çevrimdışı çalışır!',

        // ===== VIRAL-3: Template Gallery =====
        templates: 'Şablonlar',
        template_gallery: 'Şablon Galerisi',
        builtin_templates: 'Hazır Şablonlar',
        my_templates: 'Kendi Şablonlarım',
        save_as_template: 'Şablon Olarak Kaydet',
        template_name: 'Şablon adı...',
        template_applied: 'Şablon uygulandı',
        template_saved: 'Şablon kaydedildi',

        // ===== NEW TRANSLATIONS - Map Charts =====
        chart_choropleth: 'Choropleth',
        chart_bubble_map: 'Bubble Map',
        chart_flow_map: 'Flow Map',
        chart_geo_heatmap: 'Geo Heatmap',
        chart_point_map: 'Point Map',

        // ===== NEW TRANSLATIONS - Toast Messages =====
        toast_chart_settings_applied: 'Grafik ayarları uygulandı',
        toast_data_loaded_from_excel: 'Excel Studio\'dan {0} satır veri yüklendi',
        toast_data_saved_to_session: 'Veri sessionStorage\'a kaydedildi',
        toast_session_save_error: 'SessionStorage kayıt hatası',
        toast_video_not_found: 'Video bulunamadı',
        toast_video_load_failed: 'Video yüklenemedi. Dosya mevcut olmayabilir.',
        toast_feedback_min_chars: 'Lütfen en az 10 karakter içeren bir mesaj yazın',
        toast_feedback_thanks: 'Geri bildiriminiz için teşekkürler! 🙏',
        toast_dashboard_area_not_found: 'Dashboard alanı bulunamadı',
        toast_annotation_off: 'Annotation modu kapatıldı',
        toast_annotation_on: 'Annotation modu açıldı - Çizmeye başlayın!',
        toast_fabric_not_loaded: 'Fabric.js yüklenmedi, annotation kullanılamıyor',
        toast_annotations_cleared: 'Annotations temizlendi',
        toast_annotations_saved: 'Annotations kaydedildi',

        // ===== FAZ-GUIDE-1: Guided Analysis Messages =====
        guided_prefix: 'Rehberli Analiz:',
        guided_ttest_ok: 'Varsayımlar uygun görünüyor. Student\'s t-testi kullanılabilir.',
        guided_ttest_non_normal_mannwhitney: 'Normallik varsayımı sağlanmıyor. t-testi yerine Mann–Whitney U testi önerilir.',
        guided_ttest_hetero_welch: 'Varyanslar homojen değil. Welch t-testi önerilir.',
        guided_ttest_non_normal_and_hetero_mannwhitney: 'Normallik ve homojenlik varsayımları zayıf. Mann–Whitney U testi önerilir.',
        guided_paired_ok: 'Varsayımlar uygun görünüyor. Eşleştirilmiş t-testi kullanılabilir.',
        guided_paired_non_normal_wilcoxon: 'Fark puanları normal dağılmıyor. Wilcoxon işaretli sıralar testi önerilir.',
        guided_one_sample_ok: 'Varsayımlar uygun görünüyor. Tek örneklem t-testi kullanılabilir.',
        guided_one_sample_non_normal_sign_wilcoxon: 'Normallik varsayımı sağlanmıyor. Wilcoxon işaretli sıralar / İşaret testi düşünülebilir.',
        guided_anova_ok: 'Varsayımlar uygun görünüyor. Tek yönlü ANOVA kullanılabilir.',
        guided_anova_homo_tukey: 'Varyanslar homojen. Post-hoc için Tukey HSD önerilir.',
        guided_anova_hetero_gameshowell: 'Varyanslar homojen değil. Post-hoc için Games–Howell önerilir.',
        guided_anova_non_normal_kruskal: 'Normallik varsayımı zayıf. ANOVA yerine Kruskal–Wallis testi düşünülebilir.',
        guided_toggle_on: 'Rehberli Analiz: Açık',
        guided_toggle_off: 'Rehberli Analiz: Kapalı',

        // ===== FAZ-ADV-5: Cox Regression =====
        stat_cox: 'Cox Regresyon',
        cox_model_summary: 'Model Özeti',
        cox_omnibus_tests: 'Omnibus Testleri',
        cox_variables: 'Denklemdeki Değişkenler',
        cox_hazard_ratio: 'Tehlike Oranı',
        cox_convergence_ok: 'Model yakınsadı',
        cox_convergence_fail: 'Model yakınsamadı',
        cox_time_col: 'Süre Sütunu',
        cox_event_col: 'Olay Sütunu (1=olay, 0=sansürlü)',
        cox_covariates: 'Kovaryatlar',

        // ===== FAZ-1: Macro Studio Pro =====
        module_macro: 'Macro Studio',
        macro_studio_title: 'Macro Studio Pro',
        macro_scenario_list: 'Makro Senaryoları',
        macro_file_select: '1. Dosyayı Yükle',
        macro_file_placeholder: 'Excel Dosya Seç (.xlsx, .xlsm)',
        macro_sheet_select: 'Sayfa Seç',
        macro_column_select: 'Sütun Seç',
        macro_preview: 'Önizleme',
        macro_settings: '2. Makro Ayarları',
        macro_no_selection: 'Lütfen soldan bir makro senaryosu seçin.',
        macro_waiting_selection: 'Seçim Bekleniyor...',
        macro_run: 'Çalıştır',
        macro_queue_info: 'Büyük dosya kuyruğa alınıyor...',
        macro_help_placeholder: 'Detaylar için senaryo seçin.',
        macro_no_macros: 'Henüz makro senaryosu bulunmuyor',

        // ===== FAZ-4: Diff + Decision Trace =====
        diff_title: 'Değişiklik Özeti',
        diff_rows_added: 'satır eklendi',
        diff_rows_removed: 'satır silindi',
        diff_cols_added: 'yeni sütun',
        diff_cols_removed: 'sütun kaldırıldı',
        diff_detailed: 'Detaylı Diff',
        diff_no_changes: 'Değişiklik yok',
        trace_title: 'İşlem Geçmişi',
        trace_what_happened: 'Ne yapıldı',
        trace_result: 'Sonuç',
        trace_duration: 'Süre',
        trace_risk_score: 'Risk Skoru',
        trace_data_loss_risk: 'Veri Kaybı Riski',
        trace_type_mismatch: 'Tip Uyumsuzluğu',
        trace_low_risk: 'Düşük',
        trace_medium_risk: 'Orta',
        trace_high_risk: 'Yüksek',
        trace_rows_processed: 'İşlenen Satır',

        // ===== FAZ-5: Smart Suggestions =====
        suggest_title: 'Akıllı Öneri',
        suggest_add_aggregate: 'Gruplama sonrası toplama işlemi önerilir',
        suggest_check_empty: 'Filtre sonucu boş olabilir, kontrol ekleyin',
        suggest_numeric_sum: 'Sayısal sütun için toplama uygundur',
        suggest_date_extract: 'Tarih sütunundan yıl/ay çıkarabilirsiniz',
        suggest_duplicates: 'Tekrar eden değerler tespit edildi',
        suggest_nulls: 'Boş değerler mevcut, temizleme önerilir',
        suggest_text_clean: 'Metin sütunları temizlenebilir',
        suggest_apply: 'Uygula',
        suggest_dismiss: 'Reddet',
        suggest_dismissed: 'Öneri reddedildi',
        suggest_applied: 'Öneri uygulandı'
    },
    en: {
        viz_subtitle: 'Visual Studio',
        module_excel: 'Excel Studio',
        module_viz: 'Visual Studio',
        module_pdf: 'PDF Tools',
        module_ocr: 'OCR Lab',
        data_columns: 'Data Columns',
        drop_excel: 'Drop Excel file here',
        no_data_loaded: 'Load data',
        chart_types: 'Chart Types',
        chart_bar: 'Bar',
        chart_line: 'Line',
        chart_pie: 'Pie',
        chart_area: 'Area',
        chart_scatter: 'Scatter',
        chart_doughnut: 'Doughnut',
        dashboard: 'Dashboard',
        live: 'LIVE',
        add_chart: 'Add Chart',
        empty_dashboard_title: 'Your Dashboard is Empty',
        empty_dashboard_desc: 'Drag a chart type from left panel or click "Add Chart"',
        chart_settings: 'Chart Settings',
        select_chart: 'Select a chart to edit',
        chart_title: 'Chart Title',
        x_axis: 'X Axis (Category)',
        y_axis: 'Y Axis (Value)',
        aggregation: 'Aggregation',
        agg_sum: 'Sum',
        agg_avg: 'Average',
        agg_count: 'Count',
        agg_min: 'Minimum',
        agg_max: 'Maximum',
        color: 'Color',
        apply: 'Apply',
        delete_chart: 'Delete Chart',
        save: 'Save',
        export: 'Export',
        file_loaded: 'File loaded',
        error: 'Error',
        chart_added: 'Chart added',
        export_png: 'Download as PNG',
        export_pdf: 'Download as PDF',
        save_dashboard: 'Save Dashboard',
        load_dashboard: 'Load Dashboard',
        dashboard_saved: 'Dashboard saved',
        dashboard_loaded: 'Dashboard loaded',
        no_saved_dashboard: 'No saved dashboard found',
        export_success: 'Export successful',
        loading: 'Loading...',
        stats_overlay: 'Statistics Overlay',
        show_mean: 'Mean Line',
        show_median: 'Median Line',
        show_std_band: 'Std Deviation Band (±1σ)',
        show_trend: 'Trend Line',
        stats_summary: 'Statistics Summary',
        stat_mean: 'Mean',
        stat_median: 'Median',
        stat_stdev: 'Std Dev',
        stat_min: 'Min',
        stat_max: 'Max',
        stat_count: 'Count',
        basic_charts: 'Basic',
        advanced_charts: 'Advanced',
        chart_dual_axis: 'Dual-Axis',
        chart_stacked: 'Stacked',
        chart_treemap: 'Treemap',
        chart_heatmap: 'Heatmap',
        chart_funnel: 'Funnel',
        chart_gauge: 'Gauge',
        chart_waterfall: 'Waterfall',
        chart_radar: 'Radar',
        chart_boxplot: 'Box Plot',
        chart_pareto: 'Pareto',
        '3d_charts': '3D',
        chart_scatter3d: '3D Scatter',
        chart_bar3d: '3D Bar',
        chart_surface3d: '3D Surface',
        chart_line3d: '3D Line',
        statistical_analysis: 'Statistical Analysis',
        bi_insights: 'BI Insights',
        data_profile: 'Data Profile',
        run_analysis: 'Run Analysis',
        what_if_simulator: 'What-If Simulator',
        anomaly_detection: 'Anomaly Detection',
        trend_insight: 'Trend Insight',
        regression_type: 'Regression Type',
        linear: 'Linear',
        polynomial: 'Polynomial',
        exponential: 'Exponential',
        logarithmic: 'Logarithmic',
        t_test: 't-Test',
        anova: 'ANOVA',
        correlation: 'Correlation',
        normality: 'Normality',
        cross_filter: 'Cross Filter',
        detect_anomalies: 'Detect Anomalies',
        anomalies_found: 'anomalies found',
        no_anomaly: 'No anomaly detected ✓',
        trend_up: 'Upward trend detected',
        trend_down: 'Downward trend detected',
        trend_stable: 'Stable (no significant trend)',
        data_analysis: 'Data Analysis',
        total_rows: 'Total Rows',
        total_columns: 'Total Columns',
        data_quality: 'Data Quality',
        column_types: 'Column Types',
        missing_values: 'Missing Values',
        no_missing: 'No missing values ✓',
        google_sheets_title: 'Google Sheets Connection',
        google_sheets_desc: 'Enter Spreadsheet ID to fetch data from Google Sheets or connect via OAuth.',
        spreadsheet_id: 'Spreadsheet ID',
        spreadsheet_id_hint: 'Code between /d/ and /edit in URL',
        sheet_name: 'Sheet Name (optional)',
        fetch_data: 'Fetch Data',
        connect_google: 'Connect with Google (OAuth)',
        sql_title: 'SQL Data Source',
        connection_string: 'Connection String',
        connection_hint: 'PostgreSQL, MySQL, SQLite, SQL Server supported',
        test_connection: 'Test Connection',
        sql_query: 'SQL Query (SELECT only)',
        max_rows: 'Max Rows',
        run_query: 'Run Query',
        tables: 'Tables',
        collab_title: 'Live Collaboration',
        collab_desc: 'Work together on the same dashboard in real-time.',
        room_id: 'Room ID',
        username: 'Username',
        join_room: 'Join Room',
        connected: 'Connected',
        users: 'User',
        schedule_title: 'Scheduled Reports',
        report_name: 'Report Name',
        recipients: 'Recipients (comma separated)',
        period: 'Period',
        daily: 'Daily',
        weekly: 'Weekly',
        monthly: 'Monthly',
        time: 'Time',
        format: 'Format',
        create_report: 'Create Report',
        existing_reports: 'Existing Reports',
        active: 'Active',
        inactive: 'Inactive',
        stop: 'Stop',
        start: 'Start',
        run_now: 'Run Now',
        join_title: 'Data Join (JOIN)',
        left_table: 'Left Table',
        right_table: 'Right Table',
        left_key: 'Left Key Column',
        right_key: 'Right Key Column',
        join_type: 'Join Type',
        left_join: 'Left Join (All rows from left)',
        inner_join: 'Inner Join (Common rows)',
        outer_join: 'Outer Join (All rows)',
        right_join: 'Right Join (All rows from right)',
        merge: 'Merge',
        merging: 'Merging...',
        merged_success: 'Merged!',
        rows_created: 'rows created',
        regression_title: 'Regression Analysis',
        target_variable: 'Target Variable (Y)',
        predictor_variables: 'Predictor Variables (X)',
        regression_type_label: 'Regression Type',
        linear_reg: 'Linear',
        polynomial_reg: 'Polynomial (2nd degree)',
        logistic_reg: 'Logistic (For binary target)',
        analyze: 'Analyze',
        coefficients: 'Coefficients',
        regression_complete: 'Regression complete',
        insights_title: 'Smart Insights',
        analyzed: 'Analyzed',
        rows: 'rows',
        columns: 'columns',
        add_as_widget: 'Add as Widget',
        calculating_insights: 'Calculating insights...',
        need_two_datasets: 'At least 2 datasets required for JOIN. Load two files first.',
        dataset_files_not_found: 'Dataset files not found',
        load_data_first: 'Load a file first',
        need_two_numeric: 'At least 2 numeric columns required for regression',
        select_one_predictor: 'Select at least 1 predictor variable',
        spreadsheet_id_required: 'Spreadsheet ID required',
        connection_required: 'Connection and query required',
        room_id_required: 'Room ID required',
        report_name_required: 'Report name and at least 1 recipient required',
        connection_success: 'Connection successful!',
        joined_room: 'joined room!',
        left_room: 'Left collaboration room',
        connection_closed: 'Collaboration connection closed',
        user_joined: 'joined the room',
        user_left: 'left the room',
        loading_reports: 'Loading...',
        no_reports_yet: 'No scheduled reports yet',
        oauth_window_opened: 'Google OAuth window opened',
        loaded_from_sheets: 'rows loaded from Google Sheets',
        loaded_from_sql: 'rows loaded from SQL',
        row_limit: 'row limit',
        pdf_preview: 'PDF Preview',
        download_pdf: 'Download PDF',
        close: 'Close',
        statistics: 'Statistical Analysis',
        special_charts: 'Special Charts',
        map_charts: 'Map Charts',
        data_management: 'Data Management',
        select_dataset: 'Dataset',
        theme_changed: 'Theme changed',
        pdf_generating: 'Generating PDF...',
        pdf_ready: 'PDF ready',
        y_axes: 'Y Axes (Values)',
        multi_select_hint: 'Ctrl+Click for multiple selection',
        use_right_axis: 'Show second series on right axis',
        right_axis_column: 'Right Axis Column',
        scatter_x_hint: 'Multi-X selection enabled for Scatter (Ctrl+Click)',

        // ===== NEW TRANSLATIONS - Data Management Actions =====
        action_filter: 'Filter',
        action_sort: 'Sort',
        action_profile: 'Profile',
        action_undo: 'Undo',
        action_redo: 'Redo',
        action_fill_missing: 'Fill Missing',
        action_remove_outliers: 'Remove Outliers',
        action_remove_duplicates: 'Remove Duplicates',
        action_convert_type: 'Convert Type',
        action_merge_columns: 'Merge Columns',
        action_split_column: 'Split Column',
        action_find_replace: 'Find/Replace',
        action_binning: 'Binning',
        action_pivot: 'Pivot',
        action_calculated: 'Calculated',
        action_load_url: 'Load from URL',
        action_add_file: 'Add File',

        // ===== NEW TRANSLATIONS - Tools =====
        tools_category: 'Tools',
        tool_watermark: 'Watermark',
        tool_report_settings: 'Report Settings',
        tool_video_help: 'Video Help',
        tool_export_annotated: 'Export with Notes',

        // ===== NEW TRANSLATIONS - Stat Buttons =====
        drag_to_dashboard: '🎯 Drag to Dashboard',
        stat_ttest: 't-Test',
        stat_anova: 'ANOVA',
        stat_chi: 'Chi²',
        stat_correlation: 'Correlation',
        stat_normality: 'Normality',
        stat_descriptive: 'Descriptive',
        stat_mannwhitney: 'Mann-Whitney',
        stat_wilcoxon: 'Wilcoxon',
        stat_kruskal: 'Kruskal-Wallis',
        stat_levene: 'Levene',
        stat_effect_size: 'Effect Size',
        stat_frequency: 'Frequency',
        stat_pca: 'PCA',
        stat_kmeans: 'K-Means',
        stat_cronbach: 'Cronbach α',
        stat_logistic: 'Logistic Reg.',
        stat_timeseries: 'Time Series',
        stat_apa: 'APA Report',
        stat_friedman: 'Friedman',
        stat_power: 'Power Analysis',
        stat_regression: 'Regression',
        stat_discriminant: 'Discriminant',
        stat_survival: 'Survival',

        // ===== NEW TRANSLATIONS - Special Charts =====
        chart_histogram: 'Histogram',
        chart_bubble: 'Bubble',
        chart_sankey: 'Sankey',
        chart_sunburst: 'Sunburst',
        chart_polar: 'Polar',
        chart_lollipop: 'Lollipop',
        chart_bullet: 'Bullet',
        chart_step: 'Step Line',
        chart_calendar: 'Calendar',
        chart_candlestick: 'Candlestick',
        chart_violin: 'Violin',
        chart_gantt: 'Gantt',
        chart_grouped_bar: 'Grouped Bar',
        chart_word_cloud: 'Word Cloud',
        chart_timeline: 'Timeline',
        chart_chord: 'Chord',
        chart_parallel: 'Parallel',
        chart_range_area: 'Range Area',
        chart_density: 'Density',

        // ===== FAZ-ST4: Coming Soon Charts =====
        coming_soon_charts: 'Coming Soon',
        coming_soon: 'Coming Soon',
        chart_globe: 'Globe',
        chart_graph: 'Graph',

        // ===== VIRAL-1: Try Demo =====
        try_demo: 'Try Demo | Demo Dene',

        // ===== VIRAL-2: Standalone HTML =====
        standalone_html: 'Standalone HTML ✈️',
        standalone_html_creating: 'Creating Standalone HTML...',
        standalone_html_success: 'Standalone HTML downloaded - Works offline!',

        // ===== VIRAL-3: Template Gallery =====
        templates: 'Templates',
        template_gallery: 'Template Gallery',
        builtin_templates: 'Built-in Templates',
        my_templates: 'My Templates',
        save_as_template: 'Save as Template',
        template_name: 'Template name...',
        template_applied: 'Template applied',
        template_saved: 'Template saved',

        // ===== NEW TRANSLATIONS - Map Charts =====
        chart_choropleth: 'Choropleth',
        chart_bubble_map: 'Bubble Map',
        chart_flow_map: 'Flow Map',
        chart_geo_heatmap: 'Geo Heatmap',
        chart_point_map: 'Point Map',

        // ===== NEW TRANSLATIONS - Toast Messages =====
        toast_chart_settings_applied: 'Chart settings applied',
        toast_data_loaded_from_excel: '{0} rows loaded from Excel Studio',
        toast_data_saved_to_session: 'Data saved to sessionStorage',
        toast_session_save_error: 'SessionStorage save error',
        toast_video_not_found: 'Video not found',
        toast_video_load_failed: 'Video could not be loaded. File may not exist.',
        toast_feedback_min_chars: 'Please enter a message with at least 10 characters',
        toast_feedback_thanks: 'Thank you for your feedback! 🙏',
        toast_dashboard_area_not_found: 'Dashboard area not found',
        toast_annotation_off: 'Annotation mode disabled',
        toast_annotation_on: 'Annotation mode enabled - Start drawing!',
        toast_fabric_not_loaded: 'Fabric.js not loaded, annotation unavailable',
        toast_annotations_cleared: 'Annotations cleared',
        toast_annotations_saved: 'Annotations saved',

        // ===== FAZ-GUIDE-1: Guided Analysis Messages =====
        guided_prefix: 'Guided Analysis:',
        guided_ttest_ok: 'Assumptions look acceptable. Student\'s t-test is appropriate.',
        guided_ttest_non_normal_mannwhitney: 'Normality is not met. Consider Mann–Whitney U instead of the t-test.',
        guided_ttest_hetero_welch: 'Variances are not homogeneous. Consider Welch\'s t-test.',
        guided_ttest_non_normal_and_hetero_mannwhitney: 'Normality and homogeneity are questionable. Consider Mann–Whitney U.',
        guided_paired_ok: 'Assumptions look acceptable. Paired t-test is appropriate.',
        guided_paired_non_normal_wilcoxon: 'Difference scores are not normal. Consider the Wilcoxon signed-rank test.',
        guided_one_sample_ok: 'Assumptions look acceptable. One-sample t-test is appropriate.',
        guided_one_sample_non_normal_sign_wilcoxon: 'Normality is not met. Consider a Wilcoxon signed-rank / sign test.',
        guided_anova_ok: 'Assumptions look acceptable. One-way ANOVA is appropriate.',
        guided_anova_homo_tukey: 'Variances appear homogeneous. Consider Tukey HSD for post-hoc comparisons.',
        guided_anova_hetero_gameshowell: 'Variances are not homogeneous. Consider Games–Howell for post-hoc comparisons.',
        guided_anova_non_normal_kruskal: 'Normality is questionable. Consider Kruskal–Wallis as a nonparametric alternative.',
        guided_toggle_on: 'Guided Analysis: On',
        guided_toggle_off: 'Guided Analysis: Off',

        // ===== FAZ-ADV-5: Cox Regression =====
        stat_cox: 'Cox Regression',
        cox_model_summary: 'Model Summary',
        cox_omnibus_tests: 'Omnibus Tests',
        cox_variables: 'Variables in the Equation',
        cox_hazard_ratio: 'Hazard Ratio',
        cox_convergence_ok: 'Model converged',
        cox_convergence_fail: 'Model did not converge',
        cox_time_col: 'Time Column',
        cox_event_col: 'Event Column (1=event, 0=censored)',
        cox_covariates: 'Covariates',

        // ===== FAZ-1: Macro Studio Pro =====
        module_macro: 'Macro Studio',
        macro_studio_title: 'Macro Studio Pro',
        macro_scenario_list: 'Macro Scenarios',
        macro_file_select: '1. Upload File',
        macro_file_placeholder: 'Select Excel File (.xlsx, .xlsm)',
        macro_sheet_select: 'Select Sheet',
        macro_column_select: 'Select Column',
        macro_preview: 'Preview',
        macro_settings: '2. Macro Settings',
        macro_no_selection: 'Please select a macro scenario from the left.',
        macro_waiting_selection: 'Waiting for selection...',
        macro_run: 'Run',
        macro_queue_info: 'Large file is being queued...',
        macro_help_placeholder: 'Select a scenario for details.',
        macro_no_macros: 'No macro scenarios available yet',

        // ===== FAZ-4: Diff + Decision Trace =====
        diff_title: 'Change Summary',
        diff_rows_added: 'rows added',
        diff_rows_removed: 'rows removed',
        diff_cols_added: 'new columns',
        diff_cols_removed: 'columns removed',
        diff_detailed: 'Detailed Diff',
        diff_no_changes: 'No changes',
        trace_title: 'Decision Trace',
        trace_what_happened: 'What happened',
        trace_result: 'Result',
        trace_duration: 'Duration',
        trace_risk_score: 'Risk Score',
        trace_data_loss_risk: 'Data Loss Risk',
        trace_type_mismatch: 'Type Mismatch',
        trace_low_risk: 'Low',
        trace_medium_risk: 'Medium',
        trace_high_risk: 'High',
        trace_rows_processed: 'Rows Processed',

        // ===== FAZ-5: Smart Suggestions =====
        suggest_title: 'Smart Suggestion',
        suggest_add_aggregate: 'Adding aggregation after grouping is recommended',
        suggest_check_empty: 'Filter result may be empty, consider adding a check',
        suggest_numeric_sum: 'Sum operation is suitable for numeric column',
        suggest_date_extract: 'You can extract year/month from date column',
        suggest_duplicates: 'Duplicate values detected',
        suggest_nulls: 'Empty values present, cleaning recommended',
        suggest_text_clean: 'Text columns can be cleaned',
        suggest_apply: 'Apply',
        suggest_dismiss: 'Dismiss',
        suggest_dismissed: 'Suggestion dismissed',
        suggest_applied: 'Suggestion applied'
    }
};

// Global erişim için
window.VIZ_TEXTS = VIZ_TEXTS;
